# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = false

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'horizontal'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 3
inner.vertical = 3
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
shift-ctrl-alt-slash = 'layout tiles horizontal vertical'
shift-ctrl-alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
shift-ctrl-alt-h = 'focus left'
shift-ctrl-alt-left = 'focus left'
shift-ctrl-alt-j = 'focus down'
shift-ctrl-alt-down = 'focus down'
shift-ctrl-alt-k = 'focus up'
shift-ctrl-alt-up = 'focus up'
shift-ctrl-alt-l = 'focus right'
shift-ctrl-alt-right = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
cmd-shift-ctrl-alt-h = 'move left'
cmd-shift-ctrl-alt-left = 'move left'
cmd-shift-ctrl-alt-j = 'move down'
cmd-shift-ctrl-alt-down = 'move down'
cmd-shift-ctrl-alt-k = 'move up'
cmd-shift-ctrl-alt-up = 'move up'
cmd-shift-ctrl-alt-l = 'move right'
cmd-shift-ctrl-alt-right = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
cmd-shift-ctrl-alt-minus = 'resize smart -50'
cmd-shift-ctrl-alt-equal = 'resize smart +50'
cmd-shift-ctrl-alt-0 = 'balance-sizes'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
shift-ctrl-alt-1 = 'workspace 1'
shift-ctrl-alt-2 = 'workspace 2'
shift-ctrl-alt-3 = 'workspace 3'
shift-ctrl-alt-4 = 'workspace 4'
shift-ctrl-alt-5 = 'workspace 5'
shift-ctrl-alt-6 = 'workspace 6'
shift-ctrl-alt-7 = 'workspace 7'
shift-ctrl-alt-8 = 'workspace 8'
shift-ctrl-alt-9 = 'workspace 9'
# shift-ctrl-alt-a = 'workspace A' # In your config, you can drop workspace bindings that you don't need
# shift-ctrl-alt-b = 'workspace B'
# shift-ctrl-alt-c = 'workspace C'
# shift-ctrl-alt-d = 'workspace D'
# shift-ctrl-alt-e = 'workspace E'
# shift-ctrl-alt-f = 'workspace F'
# shift-ctrl-alt-g = 'workspace G'
# shift-ctrl-alt-i = 'workspace I'
# shift-ctrl-alt-m = 'workspace M'
# shift-ctrl-alt-n = 'workspace N'
# shift-ctrl-alt-o = 'workspace O'
# shift-ctrl-alt-p = 'workspace P'
# shift-ctrl-alt-q = 'workspace Q'
# shift-ctrl-alt-r = 'workspace R'
# shift-ctrl-alt-s = 'workspace S'
# shift-ctrl-alt-t = 'workspace T'
# shift-ctrl-alt-u = 'workspace U'
# shift-ctrl-alt-v = 'workspace V'
# shift-ctrl-alt-w = 'workspace W'
# shift-ctrl-alt-x = 'workspace X'
# shift-ctrl-alt-y = 'workspace Y'
# shift-ctrl-alt-z = 'workspace Z'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
cmd-shift-ctrl-alt-1 = 'move-node-to-workspace 1'
cmd-shift-ctrl-alt-2 = 'move-node-to-workspace 2'
cmd-shift-ctrl-alt-3 = 'move-node-to-workspace 3'
cmd-shift-ctrl-alt-4 = 'move-node-to-workspace 4'
cmd-shift-ctrl-alt-5 = 'move-node-to-workspace 5'
cmd-shift-ctrl-alt-6 = 'move-node-to-workspace 6'
cmd-shift-ctrl-alt-7 = 'move-node-to-workspace 7'
cmd-shift-ctrl-alt-8 = 'move-node-to-workspace 8'
cmd-shift-ctrl-alt-9 = 'move-node-to-workspace 9'
# cmd-shift-ctrl-alt-a = 'move-node-to-workspace A'
# cmd-shift-ctrl-alt-b = 'move-node-to-workspace B'
# cmd-shift-ctrl-alt-c = 'move-node-to-workspace C'
# cmd-shift-ctrl-alt-d = 'move-node-to-workspace D'
# cmd-shift-ctrl-alt-e = 'move-node-to-workspace E'
# cmd-shift-ctrl-alt-f = 'move-node-to-workspace F'
# cmd-shift-ctrl-alt-g = 'move-node-to-workspace G'
# cmd-shift-ctrl-alt-i = 'move-node-to-workspace I'
# cmd-shift-ctrl-alt-m = 'move-node-to-workspace M'
# cmd-shift-ctrl-alt-n = 'move-node-to-workspace N'
# cmd-shift-ctrl-alt-o = 'move-node-to-workspace O'
# cmd-shift-ctrl-alt-p = 'move-node-to-workspace P'
# cmd-shift-ctrl-alt-q = 'move-node-to-workspace Q'
# cmd-shift-ctrl-alt-r = 'move-node-to-workspace R'
# cmd-shift-ctrl-alt-s = 'move-node-to-workspace S'
# cmd-shift-ctrl-alt-t = 'move-node-to-workspace T'
# cmd-shift-ctrl-alt-u = 'move-node-to-workspace U'
# cmd-shift-ctrl-alt-v = 'move-node-to-workspace V'
# cmd-shift-ctrl-alt-w = 'move-node-to-workspace W'
# cmd-shift-ctrl-alt-x = 'move-node-to-workspace X'
# cmd-shift-ctrl-alt-y = 'move-node-to-workspace Y'
# cmd-shift-ctrl-alt-z = 'move-node-to-workspace Z'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
shift-ctrl-alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
cmd-shift-ctrl-alt-tab = 'move-workspace-to-monitor --wrap-around next'

shift-ctrl-alt-space = ['layout floating tiling']

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
shift-ctrl-alt-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = [
    'layout floating tiling',
    'mode main',
] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

shift-ctrl-alt-h = ['join-with left', 'mode main']
shift-ctrl-alt-j = ['join-with down', 'mode main']
shift-ctrl-alt-k = ['join-with up', 'mode main']
shift-ctrl-alt-l = ['join-with right', 'mode main']


[[on-window-detected]]
if.app-id = 'org.whispersystems.signal-desktop'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'ru.keepcoder.Telegram'
run = ['layout floating']
